apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-pv
spec:
  storageClassName: openldap-persistent
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/user/storage/openldap/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap
spec:
  storageClassName: openldap-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi